### ISSUE TITLE
[EPIC]: Update Folder Structure

### ISSUE THREAD

**Issue by Psypher1** [Psypher1/the-language-hub#12]
### Epic Description

Currently source files are on the root. Move them to an `src` folder

### features, Tasks and/or Bugs

- [x] Move files to src
- [x] Update json config
- [x] Make sure nothing else is broken
...

### Considerations

- Security: 
- Performance: 
- Accessibility: 
- Extensibility: 
- Scalability: 
- Usability: 
- Testability: 
- Maintainability:

**Comment by Psypher1** [comment]
The change has been made and everything is still working
