### ISSUE TITLE
[FEATURE]: Have a button play for pronounciation

### ISSUE THREAD

**Issue by Psypher1** [Psypher1/the-language-hub#15]
### Feature Summary

Currently there is phonetic descriptors on pronunciation. Consider, adding audio...

### Tasks
- [ ] Get audio data
- [ ] Figure out where to place the button
- [ ] ...

### Acceptance criteria

- [ ] each language, in addition to the phonetic, have a button.
- [ ] ...

### Scenario

For visually impaired users

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
