### ISSUE TITLE
[TASK]: Add verbs to Russian

### ISSUE THREAD

**Issue by Psypher1** [Psypher1/the-language-hub#20]
### Task Summary

A verbs file added to Russian folder

### Acceptance criteria

- [ ] a `verbs.md` file created
- [ ] common verbs added
- [ ] examples of usage
