### ISSUE TITLE
[EPIC]: Migrate Project to Astro

### ISSUE THREAD

**Issue by Psypher1** [Psypher1/the-language-hub#79]
### Epic Description

The project as a whole is static, and Next.js seems overkill now new technology is now available

### Features, Tasks and/or Bugs

- [ ] create astro project
- [ ] add necessary packages
- [ ] duplicate styling of current project while making improvements
- [ ] move learn folder to content collections
- [ ] render files from collections
- [ ] replace nextjs files with newly created files.
